

all_varlist = ['id_cnpj', 'id_cvm', 'txt_company_name', 'ticker',  'id_isin', 'processed_at', 'date',  'dt_refer', 'dt_year', 'dt_month',
'dt_safra_dre', 'dt_fim_exerc', 'dt_ini_exerc', 'cat_target', 'var_target',
'amplitude_close_high_price', 'amt_avg_adj_close_5', 'amt_std_adj_close_5', 'amt_min_adj_close_5', 'amt_max_adj_close_5',
'amt_avg_adj_close_10', 'amt_std_adj_close_10', 'amt_min_adj_close_10', 'amt_max_adj_close_10', 'amt_avg_adj_close_15',
'amt_std_adj_close_15', 'amt_min_adj_close_15', 'amt_max_adj_close_15', 'amt_avg_adj_close_20', 'amt_std_adj_close_20',
'amt_min_adj_close_20', 'amt_max_adj_close_20', 'amt_avg_adj_close_25', 'amt_std_adj_close_25', 'amt_min_adj_close_25',
'amt_max_adj_close_25', 'amt_avg_adj_close_30', 'amt_std_adj_close_30', 'amt_min_adj_close_30', 'amt_max_adj_close_30',
'amt_avg_adj_close_60', 'amt_std_adj_close_60', 'amt_min_adj_close_60', 'amt_max_adj_close_60', 'amt_avg_adj_close_90',
'amt_std_adj_close_90', 'amt_min_adj_close_90', 'amt_max_adj_close_90', 'amt_avg_adj_close_120', 'amt_std_adj_close_120',
'amt_min_adj_close_120', 'amt_max_adj_close_120', 'amt_avg_adj_close_160', 'amt_std_adj_close_160', 'amt_min_adj_close_160',
'amt_max_adj_close_160', 'amt_avg_adj_close_180', 'amt_std_adj_close_180', 'amt_min_adj_close_180', 'amt_max_adj_close_180',
'amt_avg_adj_close_360', 'amt_std_adj_close_360', 'amt_min_adj_close_360', 'amt_max_adj_close_360', 'pct_tx_adj_close_5d',
'pct_tx_adj_close_10d', 'pct_tx_adj_close_15d', 'pct_tx_adj_close_20d', 'pct_tx_adj_close_25d', 'pct_tx_adj_close_30d',
'pct_tx_adj_close_60d', 'pct_tx_adj_close_90d', 'pct_tx_adj_close_120d', 'pct_tx_adj_close_160d', 'pct_tx_adj_close_180d',
'pct_tx_adj_close_360d', 'pct_tx_high_price_5d', 'pct_tx_high_price_10d', 'pct_tx_high_price_15d', 'pct_tx_high_price_20d',
'pct_tx_high_price_25d', 'pct_tx_high_price_30d', 'pct_tx_high_price_60d', 'pct_tx_high_price_90d', 'pct_tx_high_price_120d',
'pct_tx_high_price_160d', 'pct_tx_high_price_180d', 'pct_tx_high_price_360d', 'pct_tx_low_price_5d', 'pct_tx_low_price_10d',
'pct_tx_low_price_15d', 'pct_tx_low_price_20d', 'pct_tx_low_price_25d', 'pct_tx_low_price_30d', 'pct_tx_low_price_60d',
'pct_tx_low_price_90d', 'pct_tx_low_price_120d', 'pct_tx_low_price_160d', 'pct_tx_low_price_180d', 'pct_tx_low_price_360d',
'pct_tx_amplitude_close_high_price_5d', 'pct_tx_amplitude_close_high_price_10d', 'pct_tx_amplitude_close_high_price_15d',
'pct_tx_amplitude_close_high_price_20d', 'pct_tx_amplitude_close_high_price_25d', 'pct_tx_amplitude_close_high_price_30d',
'pct_tx_amplitude_close_high_price_60d', 'pct_tx_amplitude_close_high_price_90d', 'pct_tx_amplitude_close_high_price_120d',
'pct_tx_amplitude_close_high_price_160d', 'pct_tx_amplitude_close_high_price_180d', 'pct_tx_amplitude_close_high_price_360d',
'amt_beta_adj_close_11', 'amt_beta_adj_close_16', 'amt_beta_adj_close_21', 'amt_beta_adj_close_26', 'amt_beta_adj_close_31',
'amt_beta_adj_close_61', 'amt_beta_adj_close_91', 'amt_beta_adj_close_121', 'amt_beta_adj_close_161', 'amt_beta_adj_close_181',
'amt_beta_adj_close_361', 'cat_adj_close_broke_high_5', 'cat_adj_close_broke_high_10', 'cat_adj_close_broke_high_15',
'cat_adj_close_broke_high_20', 'cat_adj_close_broke_high_25', 'cat_adj_close_broke_high_30', 'cat_adj_close_broke_high_60',
'cat_adj_close_broke_high_90', 'cat_adj_close_broke_high_120', 'cat_high_price_broke_high_5', 'cat_high_price_broke_high_10',
'cat_high_price_broke_high_15', 'cat_high_price_broke_high_20', 'cat_high_price_broke_high_25', 'cat_high_price_broke_high_30',
'cat_high_price_broke_high_60', 'cat_high_price_broke_high_90', 'cat_high_price_broke_high_120', 'cat_adj_close_broke_low_5',
'cat_low_price_broke_low_5', 'cat_adj_close_broke_low_10', 'cat_low_price_broke_low_10', 'cat_adj_close_broke_low_15',
'cat_low_price_broke_low_15', 'cat_adj_close_broke_low_20', 'cat_low_price_broke_low_20', 'cat_adj_close_broke_low_25',
'cat_low_price_broke_low_25', 'cat_adj_close_broke_low_30', 'cat_low_price_broke_low_30', 'cat_adj_close_broke_low_60',
'cat_low_price_broke_low_60', 'cat_adj_close_broke_low_90', 'cat_low_price_broke_low_90', 'cat_adj_close_broke_low_120',
'cat_low_price_broke_low_120', 'amt_IFR_adj_close_10', 'amt_IFR_adj_close_15', 'amt_IFR_adj_close_20', 'amt_IFR_adj_close_25',
'amt_IFR_adj_close_30', 'amt_IFR_adj_close_60', 'amt_IFR_adj_close_90', 'amt_IFR_adj_close_120',
'amt_cost_goods_and_services', 'amt_earnings_before_income_tax_and_social_contribution', 'amt_earnings_before_interest_and_taxes',
'amt_financial_results', 'amt_groos_revenue', 'amt_net_profit', 'amt_operating_revenues_and_expenses', 'amt_sales_revenue',
'amt_tot_amt_sales_revenue_1m_lag', 'amt_tot_amt_sales_revenue_1y_lag', 'amt_tot_amt_cost_goods_and_services_1m_lag',
'amt_tot_amt_cost_goods_and_services_1y_lag', 'amt_tot_amt_earnings_before_interest_and_taxes_1m_lag',
'amt_tot_amt_earnings_before_interest_and_taxes_1y_lag', 'amt_tot_amt_financial_results_1m_lag', 'amt_tot_amt_financial_results_1y_lag', 
'amt_tot_amt_net_profit_1m_lag', 'amt_tot_amt_net_profit_1y_lag', 'pct_tx_amt_sales_revenue_1m', 'pct_tx_amt_sales_revenue_1y',
'pct_tx_amt_cost_goods_and_services_1m', 'pct_tx_amt_cost_goods_and_services_1y', 'pct_tx_amt_earnings_before_interest_and_taxes_1m',
'pct_tx_amt_earnings_before_interest_and_taxes_1y', 'pct_tx_amt_financial_results_1m', 'pct_tx_amt_financial_results_1y',
'pct_tx_amt_net_profit_1m', 'pct_tx_amt_net_profit_1y', 'amt_avg_amt_sales_revenue_1', 'amt_avg_amt_sales_revenue_2',
'amt_avg_amt_sales_revenue_3', 'amt_avg_amt_sales_revenue_4', 'amt_avg_amt_cost_goods_and_services_1',
'amt_avg_amt_cost_goods_and_services_2', 'amt_avg_amt_cost_goods_and_services_3', 'amt_avg_amt_cost_goods_and_services_4',
'amt_avg_amt_earnings_before_interest_and_taxes_1', 'amt_avg_amt_earnings_before_interest_and_taxes_2',
'amt_avg_amt_earnings_before_interest_and_taxes_3', 'amt_avg_amt_earnings_before_interest_and_taxes_4',
'amt_avg_amt_financial_results_1', 'amt_avg_amt_financial_results_2', 'amt_avg_amt_financial_results_3',
'amt_avg_amt_financial_results_4', 'amt_avg_amt_net_profit_1', 'amt_avg_amt_net_profit_2', 'amt_avg_amt_net_profit_3',
'amt_avg_amt_net_profit_4', 'amt_std_amt_sales_revenue_1', 'amt_std_amt_sales_revenue_2', 'amt_std_amt_sales_revenue_3',
'amt_std_amt_sales_revenue_4', 'amt_std_amt_cost_goods_and_services_1', 'amt_std_amt_cost_goods_and_services_2',
'amt_std_amt_cost_goods_and_services_3', 'amt_std_amt_cost_goods_and_services_4', 'amt_std_amt_earnings_before_interest_and_taxes_1',
'amt_std_amt_earnings_before_interest_and_taxes_2', 'amt_std_amt_earnings_before_interest_and_taxes_3',
'amt_std_amt_earnings_before_interest_and_taxes_4', 'amt_std_amt_financial_results_1', 'amt_std_amt_financial_results_2',
'amt_std_amt_financial_results_3', 'amt_std_amt_financial_results_4', 'amt_std_amt_net_profit_1', 'amt_std_amt_net_profit_2',
'amt_std_amt_net_profit_3', 'amt_std_amt_net_profit_4', 'amt_beta_amt_sales_revenue_3', 'amt_beta_amt_cost_goods_and_services_3',
'amt_beta_amt_earnings_before_interest_and_taxes_3', 'amt_beta_amt_financial_results_3', 'amt_beta_amt_net_profit_3',
'amt_beta_amt_sales_revenue_6', 'amt_beta_amt_cost_goods_and_services_6', 'amt_beta_amt_earnings_before_interest_and_taxes_6',
'amt_beta_amt_financial_results_6', 'amt_beta_amt_net_profit_6', 'amt_beta_amt_sales_revenue_12', 'amt_beta_amt_cost_goods_and_services_12',
'amt_beta_amt_earnings_before_interest_and_taxes_12', 'amt_beta_amt_financial_results_12', 'amt_beta_amt_net_profit_12']